### ISSUE TITLE
不支持多个cron自动切换么？

### ISSUE THREAD

**Issue by ushuz** [sinacloud/sae-python-dev-guide#78]
``` yaml
cron:
- description: Chill
  url: update
  schedule: "2 0 */7 4,5,10,11 *"
- description: Hot
  url: update
  schedule: "2 */3 * 1,2,6,7 *"
- description: Warm
  url: update
  schedule: "2 0 * 3,8,9,12 *"
```

我在config.yaml里设置了多个cron，覆盖了全年，但我发现只有放在最后的那个cron是有效的，会在cronmng面板显示。

难道SAE不支持多个cron并根据现在的时间自动切换，只能手动把当期的cron排到最下面么？
